# Generated by Django 4.1 on 2022-08-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.TextField()),
                ('n_times_reviewed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ability')),
            ],
        ),
        migrations.CreateModel(
            name='AfterWhenToReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_when_to_review', models.DateTimeField(auto_now_add=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ability')),
            ],
        ),
    ]
