# Generated by Django 4.1 on 2022-08-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterwhentoreview',
            old_name='ability',
            new_name='ability_bubu',
        ),
    ]
