# Generated by Django 4.1 on 2022-08-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_ability_afterwhentoreview_ability_bubu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterwhentoreview',
            old_name='ability_bubu',
            new_name='ability',
        ),
    ]
