# Generated by Django 4.1 on 2022-08-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_ability_created_at_answers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
