# Generated by Django 4.1 on 2022-08-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_ability_created_at_alter_answers_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_times_reviewed', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ability')),
            ],
        ),
    ]
