# Generated by Django 4.1 on 2022-09-17 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_minimumabilitiesreviewedperday'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
