# Generated by Django 4.1 on 2022-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_ability_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
