# Generated by Django 4.1 on 2022-09-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_typeofability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='base.typeofability'),
        ),
    ]
