# Generated by Django 4.1 on 2022-10-01 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_diary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='answer_correctness',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
    ]
