# Generated by Django 4.1 on 2022-10-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAbilitiesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_at', models.DateTimeField(auto_now_add=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ability')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_at', models.DateTimeField(auto_now_add=True)),
                ('days_to_present_again', models.PositiveSmallIntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ability')),
            ],
        ),
    ]
