# Generated by Django 4.1 on 2022-10-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_scheduleabilitieshistory_scheduleabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleabilities',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ability'),
        ),
    ]
