# Generated by Django 4.1 on 2022-10-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_scheduleabilities_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleabilitieshistory',
            options={'get_latest_by': 'presented_at'},
        ),
    ]
