# Generated by Django 4.1 on 2022-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_ability_days_to_present_again_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='last_presentation_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
