# Generated by Django 4.1 on 2022-10-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_timestudyingtopic_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestudyingtopic',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
