# Generated by Django 4.1 on 2022-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_timestudyingtopic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='n_times_reviewed',
            field=models.IntegerField(),
        ),
    ]
